### ISSUE TITLE
Crash when refreshing too quickly

### ISSUE THREAD

**Issue by ThomasTJdev** [dom96/jester#146]
Perhaps this issue should be at httpbeast's repo, but I encountered it when using Jester.

If the end user refresh a page quickly multiple times the program crash with:
```nim
main.nim(1193)           main  # This is where `routes:` start
jester.nim(381)          serve
httpbeast.nim(388)       run
httpbeast.nim(267)       eventLoop
httpbeast.nim(160)       processEvents
system.nim(3810)         failedAssertImpl
system.nim(3803)         raiseAssert
system.nim(2857)         sysFatal
Error: unhandled exception: len(data.sendQueue) == 0  [AssertionError]
```

There is no consistency in the last GET:
1) `DEBUG   200 OK {"etag": @["5079718ceac00853f7de844fe0bb31aa"], "content-length": @["10797"], "content-type": @["application/javascript"]}`
2) `DEBUG   200 OK {"content-length": @["77444"], "content-type": @["text/html;charset=utf-8"]}`
3) `DEBUG   200 OK {"etag": @["d2f052efc0afb5607a6802f4dc35e130"], "content-length": @["28231"], "content-type": @["image/png"]}`

Nim Compiler Version 0.18.1 [Linux: amd64]
Jester@#081e5bd82e6eedeff8646e4259bd94996f3478e3

**Comment by dom96** [comment]
Can't reproduce it with a simple page. Can you give me a simple example that reproduces it + the browser you're using?

**Comment by ThomasTJdev** [comment]
My test code can be found her: https://github.com/ThomasTJdev/jester/tree/refreshcrash . It is located in `crashrefresh.nim`.

I only get encounter the error if I disable my cache. Chrome Dev-tools and check Disable cache in the Network tab.

I can only get it to crash when using `sendFile` inside the HTML code. But the reason for that could be, that I can't type F5 quickly enough, if there's not enough kb to move :) . Depending on my speed, I can crash it with between 5-50 hits on F5.

I have reproduced it when accessing Jester locally on 127.0.0.1 and behind Nginx as a reverse proxy.

Chromium: Version 67.0.3396.99 (Official Build) Arch Linux (64-bit)

## Test code
Remember to place a file names secret.jpg in the root folder.
```nim
import jester, asyncdispatch, htmlgen

routes:
  get "/secret/@filename":
    # verify access
    sendfile("public/root/" & @"filename")

  get "/pageok":
    resp h1("Hello world")

  get "/pagecrash":
    var html = "Crash due to sendfile()\n"
    html.add("<img src=\"/secret/secret.jpg\">")
    resp(html)

runForever()
```

## Error
```nim
crashrefresh.nim(3)      crashrefresh
jester.nim(381)          serve
httpbeast.nim(388)       run
httpbeast.nim(267)       eventLoop
httpbeast.nim(160)       processEvents
system.nim(3810)         failedAssertImpl
system.nim(3803)         raiseAssert
system.nim(2857)         sysFatal
Error: unhandled exception: len(data.sendQueue) == 0  [AssertionError]
```

**Comment by dom96** [comment]
This should be fixed now with latest HttpBeast.

**Comment by dom96** [comment]
Yes, you've got a Nim devel that's more strict at compile-time.

**Comment by dom96** [comment]
Should be fixed now. Btw, get httpbeast HEAD.

**Comment by ThomasTJdev** [comment]
My mistake not for testing before updating Nim devel - and you are pretty fast, I just rolled Nim devel back to #b625e6115cb3194790bde725fa12ce42a4f9e81a. But here I'm getting:
```
/home/user/nim/jester/jester.nim(612, 3) Error: 'yield' only allowed in an iterator
```

I'll update Nim devel and HttpBeast HEAD and try again ;)

**Comment by dom96** [comment]
You've found another issue :)

Just fixed it.

**Comment by ThomasTJdev** [comment]
Glad to help ;)

Nim devel updated, cloned and `nimble install` HttpBeast and Jester, but when using sendFile(), I am still getting:
```
/home/user/.nimble/pkgs/jester-0.3.1/jester.nim(611, 3) Error: 'yield' only allowed in an iterator
```

**Comment by dom96** [comment]
Did you reinstall jester head?

**Comment by dom96** [comment]
Okay, this time it's definitely fixed. I need to start testing things more thoroughly :)

**Comment by Araq** [comment]
Yay, finally. ``sendFile`` support.

**Comment by ThomasTJdev** [comment]
A little side note. When making minor CSS or JS updates, I am forcing the user to download the new JS and CSS files instead of using from their cache by appending a version number as a param to the url.

This is now returning 404. Removing the param solves the problem.

**Link**:
```html
<link rel="stylesheet" href="/css/todo.css?v=$cfgPackageVersion">
```

**Error:**
```nim
DEBUG GET /css/todo.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
```

**Comment by ThomasTJdev** [comment]
When having multiple of these cases in a single request behind Nginx will break HttpBeast. This is for urls with and without appended params.

I'll check it out and create an issue in HttpBeast repo.

```nim
INFO Jester is making jokes at http://0.0.0.0:5000
Starting 1 threads
DEBUG GET /page2
DEBUG   200 OK Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style.css
DEBUG   304 Not Modified None[RawHeaders]
DEBUG   TCActionNothing
DEBUG GET /style2.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style3.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style4.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style5.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style6.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style7.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style8.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style9.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style10.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
DEBUG GET /style11.css?
DEBUG   404 Not Found Some(@[(key: "Content-Type", val: "text/html;charset=utf-8")])
paramurl.nim(3)          paramurl
jester.nim(462)          serve
httpbeast.nim(412)       run
httpbeast.nim(292)       eventLoop
asyncdispatch.nim(1511)  poll
asyncdispatch.nim(1277)  runOnce
asyncdispatch.nim(183)   processPendingCallbacks
asyncfutures.nim(216)    :anonymous
httpbeast.nim(212)       :anonymous
system.nim(3753)         failedAssertImpl
system.nim(3746)         raiseAssert
system.nim(2807)         sysFatal
Error: unhandled exception:
0 < len(data.sendQueue) - sendQueueBefore Request needs a response. [AssertionError]
```

```nim
import jester, asyncdispatch

routes:
  get "/page2":
    var html = "<h1>H1</h1><br>"
    html.add("<h2>H2</h2>")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style2.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style3.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style4.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style5.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style6.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style7.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style8.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style9.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style10.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style11.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style12.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style13.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style14.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style15.css?v=123\">")
    html.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"style16.css?v=123\">")
    resp(html)

runForever()
```
